// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2f88uSkXS6D8zXOAHtFFDLr7BFP4Dldo',
    appId: '1:844981238638:android:ad2803c2a05cbd67f71f7f',
    messagingSenderId: '844981238638',
    projectId: 'cubit-sample',
    storageBucket: 'cubit-sample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmgd7hiFMAsXSvtcYxVOIZRdXM2ZFs9g',
    appId: '1:844981238638:ios:a118fda6988db61bf71f7f',
    messagingSenderId: '844981238638',
    projectId: 'cubit-sample',
    storageBucket: 'cubit-sample.firebasestorage.app',
    iosBundleId: 'com.example.cubitSample',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHW6vrS6-J5Q6zaelTBVR4243Xi_gCY7Q',
    appId: '1:844981238638:web:a89504c4ddaf3c91f71f7f',
    messagingSenderId: '844981238638',
    projectId: 'cubit-sample',
    authDomain: 'cubit-sample.firebaseapp.com',
    storageBucket: 'cubit-sample.firebasestorage.app',
    measurementId: 'G-Z27SWZJEG1',
  );

}